version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:23.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli==1.11.76
            pip install -r requirements.txt
      - run:
          name: Build Docker image
          command: docker build -t supreme-parser:latest ./ 
      - run:
          name: Run tests
          command: docker run -d -v $1:/app/test-files -p 8279:8279 supreme-parser:latest pytest

# Invoke jobs via workflows
workflows:
  main:
    jobs:
      - build