# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  lint:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run:
          name: Run linter
          command: |
            pylint app/
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: "Build Docker Image"
          command: ./scripts/build.sh
      - run:
          name: "Run Docker Image"
          command: ./scripts/run.sh

# Invoke jobs via workflows
workflows:
  main:
    jobs:
      - lint
      - build:
          requires:
            - lint