version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command:
            pip install -r requirements.txt
      - run:
          name: Lint Python code
          command: |
            pip install flake8
            flake8 --exclude=.git,__pycache__,.venv .
      - run:
          name: Build Docker image
          command: docker build -t myapp:latest .
      - run:
          name: Run tests
          command: docker run myapp:latest pytest

# Invoke jobs via workflows
workflows:
  main:
    jobs:
      - build